### ISSUE TITLE
New feature: customize the Anvil logo

### ISSUE THREAD

**Issue by apoapostolov** [Handyfon/myTab#3]
The anvil logo in the upper left corner of the screen could be customized by DM to have the system/campaign logo there instead of the Foundry logo. 

![image](https://user-images.githubusercontent.com/4083812/100518798-828efc00-319c-11eb-971e-3060257847ae.png)

**Comment by Fallayn** [comment]
I second this, currently using the custom CSS module to hide the icon, customizing it like the favicon with this module would be cool!

**Comment by Handyfon** [comment]
Added in 0.3
