### ISSUE TITLE
Pause Icon Issues

### ISSUE THREAD

**Issue by jayseaseven** [Handyfon/myTab#4]
Either using a web link or a link into my icons folder, both result in a pause icon that is extended one direction, stretched out like to the limits of the screen. 
![image](https://user-images.githubusercontent.com/73178576/102676887-aaef9200-416d-11eb-9d56-4636357288f1.png)

**Comment by Handyfon** [comment]
Should be fixed in the 0.3 version

Please tell me if you have any issues

**Comment by jayseaseven** [comment]
Looks great, thank you!
