### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by modzy2** [Handyfon/myTab#7]
After setup, favicon field is populated with "icons/svg/clockwork.svg"
If I try to change this to a "/home/pi/...." etc to point to something relative to root in my foundry data directory, it doesn't work.
How to store a favicon in foundry data and set in this field?

**Comment by Handyfon** [comment]
You can either upload it on external sites or .
You put the pictures in your foundry data folder and then you just type the name. example.png
You can also put it within folders of your data folder for example /pictures/example.png
